### PR TITLE
ModelAdminMixin: Only remove 'render_inline_actions' if exists

### LINKED ISSUE #39: Potential get_fields race condition if another class filters it
Inline actions modifies `get_fields`, which is okay w/ me, but this can raise a pretty opaque error if another subclass / django admin class using `get_fields` does stuff

Ideally we could check for the item to exist before removal, or we can raise a more specific warning to the user that side-effects/mutations are happening.

An example, I have a `get_fields` that does:

```python
    def get_fields(self, request, obj=None):
        fields = [
            field
            for field in super().get_fields(request, obj)
            if hasattr(self.model, field)
        ]
```

^ I'm not saying it's the responsibility for django-inline-actions to handle my personal customization, _but_ I think it should do more to on its side for having side effects on `fields` (IMO)

Error:

```
  File ".venv/lib/python3.7/site-packages/inline_actions/admin.py", line 283, in changeform_view
    request, object_id, form_url, extra_context)
  File ".venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File ".venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File ".venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File ".venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1562, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File ".venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 669, in get_form
    fields = flatten_fieldsets(self.get_fieldsets(request, obj))
  File ".venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 330, in get_fieldsets
    return [(None, {'fields': self.get_fields(request, obj)})]
  File ".venv/lib/python3.7/site-packages/inline_actions/admin.py", line 183, in get_fields
    fields.remove('render_inline_actions')
ValueError: list.remove(x): x not in list
```

### PR DESCRIPTION
**Pull request by tony**
## Description

Please include a summary of the proposed changes.

Fixes #39

## Checklist

- [ ] Tests covering the new functionality have been added
- [ ] Code builds clean without any errors or warnings
- [ ] Documentation has been updated
- [ ] Changes have been added to the `CHANGELOG.md`
- [ ] You added yourself to the `CONTRIBUTORS.md`

### CODE REVIEW

**Review by escaped — COMMENTED** [review]
Hey @tony, thanks for your BUG report und submitting a PR. Yes, I think your changes are reasonable and I would love to release your PR as a bugfix release. Before I merge your PR, would you mind going through the checklist? thank you!

**Comment by tony** [comment]
@escaped Hi there! I did this via gh editor.

Does this need tests, in your opinion?  Or just CHANGELOG/Contributors?

Best

**Comment by escaped** [comment]
I was asking this myself and came to the conclusion that it might become handy in the future. IMO this is something that could easily be missed, when this library is refactored. Additionally, it looks like it shouldn't be too hard to come up with a test case :) 
If you need any support, please don't hesitate to ask.

**Comment by tony** [comment]
@escaped I think that tests are good, Hm..

But for smaller stuff, is it possible something like this could be merged directly?  I don't have a setup at the moment for this project. I did this via editor

**Comment by escaped** [comment]
I would prefer having a test in place before we merge this PR. Happy to help you with that, but it might take a bit before I can focus on this project again.

**Comment by escaped** [comment]
Closing in favour of https://github.com/escaped/django-inline-actions/pull/41

**Pull request closed without merging**
